version: '3'

services:
  a1:
    container_name: a1
    hostname: a1
    network_mode: "host"
    build: 
      context: ./a1/
    volumes:
      - $PWD/a1/data:/app/data
  a2:
    container_name: a2
    hostname: a2
    network_mode: "host"
    build: 
      context: ./a2/
    volumes:
      - $PWD/a2/data:/app/data
  a3:
    container_name: a3
    hostname: a3
    network_mode: "host"
    build: 
      context: ./a3/
    volumes:
      - $PWD/a3/data:/app/data