version: '3'

services:
  a1:
    container_name: a1
    hostname: a1
    network_mode: "host"
#    ports:
#      - '5005:5005'
    env_file:
      - ./env/a1.env
    build: 
      context: ./a1/
    volumes:
      - $PWD/a1/data:/app/data